### ISSUE TITLE
Error Output on "complex" TX reject

### ISSUE THREAD

**Issue by reqlez** [cloudstruct/go-cardano-submit-api#30]
Getting lots of Error 500 with generic messages, when TXs get rejected by cardano-node:

`msg":"failure communicating with node: protocol error: local-tx-submission: decode error: cbor: invalid map key type: []uint8","stacktrace":"...
`

In cardano-node logs, you see the following:    

`event":"ErrorPolicyUnhandledApplicationException (MuxError MuxBearerClosed \"<socket: 78> closed when reading data, waiting on next header True\")"},"msg":"","thread":"66","app":[]}
{"host":"freebsd","pid":"44261","loc":null,"at":"2022-05-26T06:34:37.71Z","ns":["cardano.node.LocalErrorPolicy"],"sev":"Error","env":"1.34.1:00000","data":{"kind":"ErrorPolicyTrace","address":"LocalAddress \"/node-ipc/node.socket@6759\"","event":"ErrorPolicyUnhandledApplicationException (MuxError MuxBearerClosed \"<socket: 79> closed when reading data, waiting on next header True\")"},"msg":"","thread":"66","app":[]}`

Andrew's explanation:
"we can't currently parse the "reason" CBOR because it contains maps with bytestring keys, which Go cannot natively support...
we have a similar problem when parsing blocks during chain-sync with go-ouroboros-network"

**Comment by wolf31o2** [comment]
The root cause is cloudstruct/go-ouroboros-network#85 but we can also handle the error better here.
