### ISSUE TITLE
Running submit api with local installed cardano node?

### ISSUE THREAD

**Issue by zweetdreamz** [cloudstruct/go-cardano-submit-api#79]
How can I run cardano-submit-api container collaborating with local installed cardano-node?

**Comment by agaffney** [comment]
Set the `CARDANO_NODE_SOCKET_PATH` env var to point to the location of your `cardano-node` UNIX socket. You'll probably need to map the socket into the container as a volume.

**Comment by agaffney** [comment]
There's also an example of running `cloudstruct/cardano-node` and `cloudstruct/cardano-submit-api` together, both via Docker.

https://github.com/cloudstruct/go-cardano-submit-api#together-with-cloudstructcardano-node-in-docker

**Comment by wolf31o2** [comment]
I created a PR to document this use case.
